# Generated by Django 5.1.5 on 2025-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='direccion',
        ),
    ]
