# Generated by Django 5.1.5 on 2025-02-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('manicurists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('manicurista', 'estado')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hora_cita',
        ),
    ]
