# Generated by Django 5.1.5 on 2025-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_unique_together_and_more'),
        ('manicurists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('manicurista', 'fecha_cita', 'hora_cita')},
        ),
    ]
