# Generated by Django 5.1.5 on 2025-02-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manicurists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='manicurists.manicurist')),
            ],
        ),
    ]
