# Generated by Django 5.1.5 on 2025-02-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='work',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='works/'),
        ),
    ]
