# Generated by Django 5.1.5 on 2025-02-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurists', '0001_initial'),
        ('works', '0002_remove_work_imagen_url_work_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='manicurista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='manicurists.manicurist'),
        ),
    ]
